services:
  api_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18083:80"

  chatbot_ui:
    build:
      context: ../../shared/chatbot_ui
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    environment:
      - CHAT_COMPLETION_ENDPOINT=http://host.docker.internal:10000/v1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./arch_config.yaml:/app/arch_config.yaml

  jaeger:
    build:
      context: ../../shared/jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
