receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  filter:
    include:
      attributes:
        http.url: '*/healthz'
    drop: true
  batch:
    timeout: 5s

exporters:
  otlphttp:
    endpoint: "https://logfire-api.pydantic.dev"
    headers:
      Authorization: "${LOGFIRE_API_KEY}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter, batch]
      exporters: [otlphttp]
