version: "0.1-beta"

routing:
  model: gpt-4o

listeners:
  egress_traffic:
    address: 0.0.0.0
    port: 12000
    message_format: openai
    timeout: 30s

llm_providers:

  - name: archgw-v1-router-model
    provider_interface: openai
    model: cotran2/llama-4-epoch
    base_url: http://34.46.85.85:8000/v1

  - name: gpt-4o
    provider_interface: openai
    access_key: $OPENAI_API_KEY
    model: gpt-4o
    usage: Generating original content such as scripts, articles, or creative materials.
    default: true

  - name: o4-mini
    provider_interface: openai
    access_key: $OPENAI_API_KEY
    model: o4-mini
    usage: Requesting topic ideas specifically related to personal finance and budgeting.

  - name: code_generation
    provider_interface: openai
    access_key: $OPENAI_API_KEY
    model: gpt-4.1
    usage: Generating new code snippets, functions, or boilerplate based on user prompts or requirements

  - name: code_understanding
    provider_interface: openai
    access_key: $OPENAI_API_KEY
    model: gpt-4.1
    usage: understand and explain existing code snippets, functions, or libraries

tracing:
  random_sampling: 100
