version: "0.1-beta"

routing:
  model: gpt-4o
  # model: archgw-router
  # model: claude-3.7

listeners:
  egress_traffic:
    address: 0.0.0.0
    port: 12000
    message_format: openai
    timeout: 30s

llm_providers:

  - name: gpt-4o
    provider_interface: openai
    access_key: $OPENAI_API_KEY
    model: gpt-4o
    usage: |
      complex reasoning problem, require multi step answer

  - name: o4-mini
    provider_interface: openai
    access_key: $OPENAI_API_KEY
    model: o4-mini
    usage: |
      simple requests, basic fact retrieval, easy to answer

tracing:
  random_sampling: 100
