version: v0.1

listeners:
  ingress_traffic:
    address: 0.0.0.0
    port: 10000
    message_format: openai
    timeout: 30s

llm_providers:
  - name: gpt-4o
    access_key: $OPENAI_API_KEY
    provider_interface: openai
    model: gpt-4o

endpoints:

  - name: frankfurther_api
    endpoint: api.frankfurter.dev
    protocol: https

  - name: twelvedata_api
    endpoint: api.twelvedata.com
    protocol: https

mcp:

  - name: get_currency_exchange_rate
  - name: get_list_of_supported_currencies
  - name: get_stock_quote

prompt_guards:
  input_guards:
    jailbreak:
      on_exception:
        message: Looks like you're curious about my abilities, but I can only provide assistance for currency exchange.

agents:
  - name: currency_exchange_agent
    description: Agent for handling currency exchange queries
    llm_provider: gpt-4o
    system_prompt: |
      You are a helpful assistant. Only respond to queries related to currency exchange. If there are any other questions, I can't help you.
    tools:
      - get_currency_exchange_rate
      - get_list_of_supported_currencies

  - name: get_stock_quote_agent
    description: Agent for handling stock quote queries
    llm_provider: gpt-4o
    system_prompt: |
      You are a helpful stock exchange assistant. You are given stock symbol along with its exchange rate in json format. Your task is to parse the data and present it in a human-readable format. Keep the details to highlevel and be concise.
    tools:
      - get_stock_quote

tracing:
  random_sampling: 100
  trace_arch_internal: true
