services:
  archgw:
    image: katanemo/archgw:latest
    ports:
      - "10000:10000"
      - "10001:10001"
      - "11000:11000"
      - "12000:12000"
      - "19901:9901"
    volumes:
      - ${ARCH_CONFIG_FILE:-../demos/weather_forecast/arch_config.yaml}:/config/arch_config.yaml
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem
      - ~/archgw_logs:/var/log/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:?error}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:?error}
