version: "0.1-beta"

listeners:
  egress_traffic:
    address: 0.0.0.0
    port: 12000
    message_format: openai
    timeout: 30s

llm_providers:
  - name: gpt-4o-mini
    access_key: $OPENAI_API_KEY
    provider_interface: openai
    model: gpt-4o-mini
    default: true

  - name: gpt-4o
    access_key: $OPENAI_API_KEY
    provider_interface: openai
    model: gpt-4o

  - name: ministral-3b
    access_key: $MISTRAL_API_KEY
    provider_interface: mistral
    model: ministral-3b-latest

  - name: deepseek
    access_key: $DEEPSEEK_API_KEY
    provider_interface: openai
    model: deepseek-reasoner
    base_url: https://api.deepseek.com/

  - name: groq
    access_key: $GROQ_API_KEY
    provider_interface: openai
    model: llama-3.1-8b-instant
    base_url: https://api.groq.com

tracing:
  random_sampling: 100
