version: "0.1-beta"

listeners:
  egress_traffic:
    address: 0.0.0.0
    port: 12000
    message_format: openai
    timeout: 30s

llm_providers:
  - name: gpt-4o-mini
    access_key: $OPENAI_API_KEY
    provider_interface: openai
    model: gpt-4o-mini
    default: true

  - name: gpt-3.5-turbo-0125
    access_key: $OPENAI_API_KEY
    provider_interface: openai
    model: gpt-3.5-turbo-0125

  - name: gpt-4o
    access_key: $OPENAI_API_KEY
    provider_interface: openai
    model: gpt-4o

  - name: ministral-3b
    access_key: $MISTRAL_API_KEY
    provider_interface: mistral
    model: ministral-3b-latest

tracing:
  random_sampling: 100
