version: "0.1-beta"

listeners:
  egress_traffic:
    address: 0.0.0.0
    port: 12000
    message_format: openai
    timeout: 30s

llm_providers:
  - name: gpt-4o-mini
    access_key: $OPENAI_API_KEY
    provider_interface: openai
    model: gpt-4o-mini

  - name: gpt-4o
    access_key: $OPENAI_API_KEY
    provider_interface: openai
    model: gpt-4o

  - name: ministral-3b
    access_key: $MISTRAL_API_KEY
    provider_interface: mistral
    model: ministral-3b-latest

  - name: claude-sonnet
    access_key: $ANTHROPY_API_KEY
    provider_interface: claude
    model: claude-3-7-sonnet-latest
    default: true

  - name: deepseek
    access_key: $DEEPSEEK_API_KEY
    provider_interface: deepseek
    model: deepseek-reasoner

  - name: groq
    access_key: $GROQ_API_KEY
    provider_interface: groq
    model: llama-3.1-8b-instant

tracing:
  random_sampling: 100
