version: v0.1
listener:
  address: 127.0.0.1
  port: 8080 #If you configure port 443, you'll need to update the listener with tls_certificates
  message_format: huggingface

endpoints:
  spotify:
    endpoint: api.spotify.com
    protocol: https

system_prompt: |
 You are a music assistant. Extract critical details from the JSON response from Spotify like album images, artist name and artist image and display in a neat HTML-friendly way.

llm_providers:
  - name: OpenAI
    provider_interface: openai
    access_key: $OPENAI_API_KEY
    model: gpt-4o
    default: true

prompt_targets:
  - name: browse_new_releases
    parameters:
      - name: country
        description: the country to select
        required: true
        type: str
        in_path: true
    endpoint:
      name: spotify
      path: /v1/browse/new-releases?country={country}&limit=5
      http_headers:
        Authorization: "Bearer $SPOTIFY_CLIENT_KEY"
    description: browse new album releases in spotify
