version: "0.1-beta"

listeners:
  ingress_traffic:
    address: 0.0.0.0
    port: 10000
    message_format: openai
    timeout: 30s

overrides:
  use_agent_orchestrator: true

endpoints:
  triage_service:
    endpoint: host.docker.internal:18083

llm_providers:
  - name: gpt-4o-mini
    access_key: $OPENAI_API_KEY
    provider_interface: openai
    model: gpt-4o-mini
    default: true

system_prompt: |
  You are a helpful assistant.

prompt_targets:
  - name: sales_agent
    description: handles queries related to sales and purchases
    endpoint:
      name: triage_service
      path: /sales
      http_method: POST
      pass_context: true
    auto_llm_dispatch_on_response: false

  - name: issues_and_repairs
    description: handles issues, repairs, or refunds
    endpoint:
      name: triage_service
      path: /issues
      http_method: POST
      pass_context: true
    auto_llm_dispatch_on_response: false

  - name: escalate_to_human
    description: escalates to human agent
    endpoint:
      name: triage_service
      path: /escalate
      http_method: POST
      pass_context: true
    auto_llm_dispatch_on_response: false

tracing:
  random_sampling: 100
  trace_arch_internal: true
