name: e2e tests

on:
  push:
    branches:
      - main  # Run tests on pushes to the main branch
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.10] # , 3.11, 3.12, 3.13]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          export POETRY_VERSION=1.8.5
          curl -sSL https://install.python-poetry.org | python -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Run e2e tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: |
          python -mvenv venv
          source venv/bin/activate && cd tests/e2e && bash run_e2e_tests.sh
